In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
pwd

'C:\\Users\\vkdamera'

In [6]:
os.chdir('C:\\Users\\vkdamera\\Downloads\\Batch 98 Day 25\\Batch 98 Day 25\\Data Preprocessing\\')

In [8]:
df1 = pd.read_excel ("Data Preprocessing Data File.xlsx")	
print (df1)


   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [21]:
x = df1.iloc [:,:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [10]:
y = df1.iloc [:,-1]
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased , dtype: object

In [11]:
y = df1.iloc [:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [12]:
print (x)

   Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0


In [13]:
print (y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [23]:
x = df1.iloc [:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [24]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [25]:
from sklearn.impute import SimpleImputer
ci = SimpleImputer()
ci.fit_transform(x[:,1:2])

array([[44.   ],
       [27.   ],
       [39.875],
       [39.   ],
       [39.875],
       [35.   ],
       [39.   ],
       [48.   ],
       [50.   ],
       [37.   ]])

In [26]:
from sklearn.impute import SimpleImputer
ci = SimpleImputer(strategy = 'median')
ci.fit_transform(x[:,1:2])

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [27]:
from sklearn.impute import SimpleImputer
ci = SimpleImputer(strategy = 'constant' ,fill_value = 555)
ci.fit_transform(x[:,1:2])

array([[44.0],
       [27.0],
       [555],
       [39.0],
       [555],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [28]:
print (x)

[['France ' 44.0 72000.0]
 [nan 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [29]:
from sklearn.impute import SimpleImputer
ci = SimpleImputer(strategy = 'most_frequent')
ci.fit_transform(x[:,0:1])

array([['France '],
       ['France '],
       ['Germany '],
       ['Spain '],
       ['Germany '],
       ['France '],
       ['Spain '],
       ['France '],
       ['Germany '],
       ['France ']], dtype=object)