In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import seaborn as sns

In [2]:
pwd

'C:\\Users\\vkdamera'

In [5]:
os.chdir('C:\\Users\\vkdamera\\Downloads\\Batch 98 Day 33\\Batch 98 Day 33\\CS 29 Ans -Multiple Linear Regression\\')

In [6]:
dataset = pd.read_excel('Health_Score.xlsx')
dataset

Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0          8.0               78            284            9.1   
1          9.3               68            433            8.7   
2          7.5               70            739            7.2   
3          8.9               96           1792            8.9   
4         10.2               74            477            8.3   
5          8.3              111            362           10.9   
6          8.8               77            671           10.0   
7          8.8              168            636            9.1   
8         10.7               82            329            8.7   
9         11.7               89            634            7.6   
10         8.5              149            631           10.8   
11         8.3               60            257            9.5   
12         8.2               96            284            8.8   
13         7.9               83            603            9.5   
14        10.3              130            686            8.7   
15         7.4              145            345           11.2   
16         9.6              112           1357            9.7   
17         9.3              131            544            9.6   
18        10.6               80            205            9.1   
19         9.7              130           1264            9.2   
20        11.6              140            688            8.3   
21         8.1              154            354            8.4   
22         9.8              118           1632            9.4   
23         7.4               94            348            9.8   
24         9.4              119            370           10.4   
25        11.2              153            648            9.9   
26         9.1              116            366            9.2   
27        10.5               97            540           10.3   
28        11.9              176            680            8.9   
29         8.4               75            345            9.6   
30         5.0              134            525           10.3   
31         9.8              161            870           10.4   
32         9.8              111            669            9.7   
33        10.8              114            452            9.6   
34        10.1              142            430           10.7   
35        10.9              238            822           10.3   
36         9.2               78            190           10.7   
37         8.3              196            867            9.6   
38         7.3              125            969           10.5   
39         9.4               82            499            7.7   
40         9.4              125            925           10.2   
41         9.8              129            353            9.9   
42         3.6               84            288            8.4   
43         8.4              183            718           10.4   
44        10.8              119            540            9.2   
45        10.1              180            668           13.0   
46         9.0               82            347            8.8   
47        10.0               71            345            9.2   
48        11.3              118            463            7.8   
49        11.3              121            728            8.2   
50        12.8               68            383            7.4   
51        10.0              112            316           10.4   
52         6.7              109            388            8.9   

    Population Density  
0                  109  
1                  144  
2                  113  
3                   97  
4                  206  
5                  124  
6                  152  
7                  162  
8                  150  
9                  134  
10                 292  
11                 108  
12                 111  
13                 182  
14                 129  
15                 158  
16                 186  
17                 177  
18                

In [7]:
x = dataset.iloc[:,1:].values
x

array([[  78.        ,  284.        ,    9.10000038,  109.        ],
       [  68.        ,  433.        ,    8.69999981,  144.        ],
       [  70.        ,  739.        ,    7.19999981,  113.        ],
       [  96.        , 1792.        ,    8.89999962,   97.        ],
       [  74.        ,  477.        ,    8.30000019,  206.        ],
       [ 111.        ,  362.        ,   10.89999962,  124.        ],
       [  77.        ,  671.        ,   10.        ,  152.        ],
       [ 168.        ,  636.        ,    9.10000038,  162.        ],
       [  82.        ,  329.        ,    8.69999981,  150.        ],
       [  89.        ,  634.        ,    7.5999999 ,  134.        ],
       [ 149.        ,  631.        ,   10.80000019,  292.        ],
       [  60.        ,  257.        ,    9.5       ,  108.        ],
       [  96.        ,  284.        ,    8.80000019,  111.        ],
       [  83.        ,  603.        ,    9.5       ,  182.        ],
       [ 130.        ,  686.      

In [8]:
y = dataset.iloc[:,0].values
y

array([ 8.        ,  9.30000019,  7.5       ,  8.89999962, 10.19999981,
        8.30000019,  8.80000019,  8.80000019, 10.69999981, 11.69999981,
        8.5       ,  8.30000019,  8.19999981,  7.9000001 , 10.30000019,
        7.4000001 ,  9.60000038,  9.30000019, 10.60000038,  9.69999981,
       11.60000038,  8.10000038,  9.80000019,  7.4000001 ,  9.39999962,
       11.19999981,  9.10000038, 10.5       , 11.89999962,  8.39999962,
        5.        ,  9.80000019,  9.80000019, 10.80000019, 10.10000038,
       10.89999962,  9.19999981,  8.30000019,  7.30000019,  9.39999962,
        9.39999962,  9.80000019,  3.5999999 ,  8.39999962, 10.80000019,
       10.10000038,  9.        , 10.        , 11.30000019, 11.30000019,
       12.80000019, 10.        ,  6.69999981])

In [9]:
print (x.shape)
print (y.shape)

(53, 4)
(53,)


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [11]:
print (y_test)

[ 5.          7.5        10.          9.80000019  9.80000019  9.
 10.10000038  9.39999962 10.10000038  9.69999981  8.5       ]


In [12]:
from sklearn.linear_model import LinearRegression
regressor =  LinearRegression()
regressor.fit (x_train, y_train)

LinearRegression()

In [13]:
y_pred = regressor.predict (x_test )
y_pred

array([ 8.65654845, 10.57049948,  9.12926103,  9.56518501,  9.15397193,
       10.19763099,  9.00579912, 10.3654805 ,  7.50633246,  9.20384247,
        6.60848831])

In [14]:
print (y_test)

[ 5.          7.5        10.          9.80000019  9.80000019  9.
 10.10000038  9.39999962 10.10000038  9.69999981  8.5       ]


In [15]:
y_pred = regressor.predict (x )
y_pred

array([ 9.16830283,  9.06981045, 10.57049948, 10.48822982,  8.67884787,
        8.08173424,  8.35938875,  9.24621142,  9.00537556, 10.10924015,
        6.60848831,  8.82039276,  9.4246574 ,  8.32121054,  9.71259243,
        7.66810144,  8.77961834,  8.51753078,  8.92410509,  9.20384247,
       10.56963221, 10.10241672, 10.13597454,  8.75874067,  8.84854448,
        9.62508144,  9.42764107,  8.83119857, 10.3674476 ,  9.07005095,
        8.65654845,  9.15397193,  9.56518501,  9.69600677,  9.00579912,
        9.82073492,  8.2822002 ,  9.85340539,  8.36367688, 10.3654805 ,
        9.32686798,  9.60932803,  9.63004436,  9.60756789, 10.06314535,
        7.50633246, 10.19763099,  9.77649655, 11.13822764, 10.49516297,
       10.83918806,  9.12926103,  9.68587003])

In [16]:
print (y)

[ 8.          9.30000019  7.5         8.89999962 10.19999981  8.30000019
  8.80000019  8.80000019 10.69999981 11.69999981  8.5         8.30000019
  8.19999981  7.9000001  10.30000019  7.4000001   9.60000038  9.30000019
 10.60000038  9.69999981 11.60000038  8.10000038  9.80000019  7.4000001
  9.39999962 11.19999981  9.10000038 10.5        11.89999962  8.39999962
  5.          9.80000019  9.80000019 10.80000019 10.10000038 10.89999962
  9.19999981  8.30000019  7.30000019  9.39999962  9.39999962  9.80000019
  3.5999999   8.39999962 10.80000019 10.10000038  9.         10.
 11.30000019 11.30000019 12.80000019 10.          6.69999981]


In [17]:
y_pred = pd.DataFrame(y_pred,columns= ['Prediction'])
final = pd.concat([dataset,y_pred], axis =1)
display(final)


Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0          8.0               78            284            9.1   
1          9.3               68            433            8.7   
2          7.5               70            739            7.2   
3          8.9               96           1792            8.9   
4         10.2               74            477            8.3   
5          8.3              111            362           10.9   
6          8.8               77            671           10.0   
7          8.8              168            636            9.1   
8         10.7               82            329            8.7   
9         11.7               89            634            7.6   
10         8.5              149            631           10.8   
11         8.3               60            257            9.5   
12         8.2               96            284            8.8   
13         7.9               83            603            9.5   
14        10.3              130            686            8.7   
15         7.4              145            345           11.2   
16         9.6              112           1357            9.7   
17         9.3              131            544            9.6   
18        10.6               80            205            9.1   
19         9.7              130           1264            9.2   
20        11.6              140            688            8.3   
21         8.1              154            354            8.4   
22         9.8              118           1632            9.4   
23         7.4               94            348            9.8   
24         9.4              119            370           10.4   
25        11.2              153            648            9.9   
26         9.1              116            366            9.2   
27        10.5               97            540           10.3   
28        11.9              176            680            8.9   
29         8.4               75            345            9.6   
30         5.0              134            525           10.3   
31         9.8              161            870           10.4   
32         9.8              111            669            9.7   
33        10.8              114            452            9.6   
34        10.1              142            430           10.7   
35        10.9              238            822           10.3   
36         9.2               78            190           10.7   
37         8.3              196            867            9.6   
38         7.3              125            969           10.5   
39         9.4               82            499            7.7   
40         9.4              125            925           10.2   
41         9.8              129            353            9.9   
42         3.6               84            288            8.4   
43         8.4              183            718           10.4   
44        10.8              119            540            9.2   
45        10.1              180            668           13.0   
46         9.0               82            347            8.8   
47        10.0               71            345            9.2   
48        11.3              118            463            7.8   
49        11.3              121            728            8.2   
50        12.8               68            383            7.4   
51        10.0              112            316           10.4   
52         6.7              109            388            8.9   

    Population Density  Prediction  
0                  109    9.168303  
1                  144    9.069810  
2                  113   10.570499  
3                   97   10.488230  
4                  206    8.678848  
5                  124    8.081734  
6                  152    8.359389  
7                  162    9.246211  
8                  150    9.005376  
9                  134   10.109240  
10                 292    6.608488  
11                 108    8.820393  
12          

In [18]:
regressor.coef_

array([ 0.00501226,  0.00064205, -0.62914983, -0.01130558])

In [19]:
regressor.intercept_

15.552576766444297

In [20]:
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.954
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              254.2
Date:                Mon, 02 Dec 2024   Prob (F-statistic):                    4.15e-32
Time:                        05:18:29   Log-Likelihood:                         -112.63
No. Observations:                  53   AIC:                                      233.3
Df Residuals:                      49   BIC:                                      241.1
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------